### ISSUE TITLE
Simple Voice Recorder sharing results in ZIP with no media file

### ISSUE THREAD

**Issue by makeworld-the-better-one** [guardianproject/proofmode-android#107]
As discussed in chat, I am using Simple Voice Recorder and ProofMode to sign recordings. When sharing to ProofMode using Simple Voice Recorder's in-app share button, ProofMode will generate ZIPs that don't contain any audio files. Sharing the audio file from a file manager (such as Material Files) works, although the file name in the ZIP is messed up.

At a minimum I would expect ProofMode to show an error when it can't locate file content, rather than generate an invalid output. At best, integration between these two apps would work.

ProofMode version: 0.0.16-ALPHA-3
Simple Voice Recorder: 5.9.0 (latest at time of writing)

**Comment by makeworld-the-better-one** [comment]
cc @yurkowashere

**Comment by YurkoWasHere** [comment]
Found sharing the file recorded through a file manager yields an odd path 
`content://com.android.providers.media.documents/document/audio%3A27`
However file is attached as `audio:27`

Another file manager yielded a full HTML encoded path `file://storage.....30.m4a'
