### ISSUE TITLE
 0.0.17-RC-1 auto-generated proof doesn't work on Samsung Galaxy Note 10+

### ISSUE THREAD

**Issue by shayaknyc** [guardianproject/proofmode-android#108]
Hey all, been following this project for a long time and eager to see how this develops. I've recently updated to the latest release ([0.0.17-RC-1](https://github.com/guardianproject/proofmode-android/releases/tag/0.0.17-RC-1)) on my stock, unrooted, Samsung Galaxy Note 10+. Not a single photo or video I've taken, while Proof Mode is turned ON, generates a proof. I've waited 3 minutes after having taken the photo or video to get the proof, but each time I get the "No proof exists yet" screen with the ability to manually generate the proof. The manually generated proof appears to be working ok, but then it ONLY captures sensor data at the time the button is pressed, and not at the date/time/location of the actual photo/video. 

Any ideas?

Edit: I have an external SD card, and have the images saved there automatically, so I changed the save location on the stock cam app to internal, and took another photo, thinking it might be related to not having proper permissions (not sure why tho, since I have all perms turned on). Still did not auto generate proof, even on photos/videos saved in the default internal storage DCIM location.

**Comment by shayaknyc** [comment]
Just installed  0.0.18-ALPHA-1 and used built-in camera. No proof generated. Not sure what's up.

**Comment by n8fr8** [comment]
Thanks for testing. I agree it is likely something due to path of photo storage. Strange that the built-in camera wouldn't work in that case, but definitely a good clue for debugging. We have some stock Galaxy devices around, but no Notes. Will try to reproduce,

**Comment by shayaknyc** [comment]
Yeah, I thought for sure the built-in would at least work, but nope. Happy to test where I can!

**Comment by n8fr8** [comment]
Ordered two Samsung devices (A12 and S10+) that we can hopefully reproduce this on. I know we have already been testing on A21 and found some issues there.

**Comment by n8fr8** [comment]
New alpha 2 is up: https://github.com/guardianproject/proofmode-android/releases/tag/0.0.18-ALPHA-2

that has been tested on a Samsung A12, though not using external SD storage. Will work that into the next round.

**Comment by shayaknyc** [comment]
Ok, so on my Stock, unrooted, Galaxy Note 10+ with Android 12, the built-in camera had a robust proof ready! I also tested the stock samsung camera, and the default save is the external sd, and it was able to find a proof! Now, saving the robust proof timesout and then FC's the app, but sharing a robust proof works right away without issue.

**Comment by shayaknyc** [comment]
Ok, video using both the built-in camera and stock samsung camera does not generate a proof :/ Only manually generate. Making progress tho!!!

**Comment by n8fr8** [comment]
One issue could be that videos are much bigger and take longer to process (generating hashes, etc). Perhaps wait a little longer to try and share proof before you check? This may ultimately be a user experience issue, that we should show if proof is in process of being generated already or not.

Otherwise, we'll do more testing with video AND external storage.

**Comment by shayaknyc** [comment]
So, I have a 2 second video I took using the built-in camera. It's been at least 15 minutes, and there's no proof yet. The mp4 file is 3.69mb, which is smaller than some of the photos I've taken. I don't think it's working for videos.

**Comment by n8fr8** [comment]
0.0.18 RC 1 is coming with a fix

**Comment by n8fr8** [comment]
(and an improved built in camera)
