### ISSUE TITLE
Null value when pass Signal's uri to generateProof

### ISSUE THREAD

**Issue by maxSafronovForte** [guardianproject/proofmode-android#110]
When I try to do this 

var proofHash = ProofMode.generateProof(context, uri)

in MediaCaptureRepository, when we capture photo from Signal, I pass uri from the photo 

`val uri: Uri = createBlobBuilder(BlobProvider.getInstance(), data, length)
        .withMimeType(mimeType)
        .createForSingleSessionOnDisk(context)
`

and generateProof returns null

**Comment by n8fr8** [comment]
resolved!
