### ISSUE TITLE
Two CSV files generated

### ISSUE THREAD

**Issue by ingfabby** [guardianproject/proofmode-android#111]
Version 0.0.18-ALPHA-1
Tested on Galaxy S20, Android 12
The zip file generated has 2 csv files, one with descriptions and one without them. 
[proofmode-3b8dbde530a470e5-2022-12-21-11-36-06CST.zip](https://github.com/guardianproject/proofmode-android/files/10280209/proofmode-3b8dbde530a470e5-2022-12-21-11-36-06CST.zip)

**Comment by n8fr8** [comment]
the "batchproof" csv is for different purposes. just ignore it.
