### ISSUE TITLE
Location feature doesn't enble

### ISSUE THREAD

**Issue by ingfabby** [guardianproject/proofmode-android#113]
Tested on Galaxy S20, Android 12
Version 0.0.18-ALPHA-!

If you enable the location option from the app GPS coordinates are not captured, they are only captured if you manually go to the phone settings and enable location on the app permissions section of ProofMode.

**Comment by n8fr8** [comment]
You have accidentally disabled location previously. Try a clean install of the next release and let me know what your experience is.
