### ISSUE TITLE
Bad Google Play Download Link

### ISSUE THREAD

**Issue by war59312** [guardianproject/proofmode-android#114]
The [DOWNLOAD NOW FROM GOOGLE PLAY](https://play.google.com/store/apps/details?id=org.witness.informacam.app) link on https://guardianproject.info/archive/camerav/ is a bad link.

"We're sorry, the requested URL was not found on this server."

The correct link: https://play.google.com/store/apps/details?id=org.witness.proofmode

**Comment by n8fr8** [comment]
The links seem to work for me... but anyhow, CameraV is a different and older app than ProofMode.

Thanks for the help.
