### ISSUE TITLE
Set the private key as the public key of the certificate

### ISSUE THREAD

**Issue by JeJe-LIAO** [guardianproject/proofmode-android#116]
In proofmode.camera.c2pa.C2paUtils.kt
var userCertType = CertificateType.ContentCredentials("ProofMode-User-$_identityKey", CERT_VALIDITY_DAYS)
var userCertOptions = CertificateOptions(
        userKey,
        userCertType,
        rootCert,
        _identityEmail,
        _identityKey
        )
userCert = createCertificate(userCertOptions)

and I can found function createCertificate in https://gitlab.com/guardianproject/proofmode/simple-c2pa/-/tree/main
simple-c2pa-main.src.certificat.rs as following: 

pub fn create_certificate(
    options: Arc<CertificateOptions>,
) -> Result<Arc<Certificate>, SimpleC2PAError> {
    let serial_number = generate_serial_number()?;
    let private_key = PKey::private_key_from_pem(&options.key.get_bytes()?)?;
    let is_ca = options.certificate_type.is_ca();
    let name = create_name(options.clone())?;

    let mut cert_builder = X509::builder()?;
    cert_builder.set_version(2)?;
    cert_builder.set_subject_name(&name)?;
    if let Some(parent_certificate) = options.parent_certificate.clone() {
        let parent_cert = X509::from_pem(&parent_certificate.certificate_data.get_bytes()?)?;
        cert_builder.set_issuer_name(parent_cert.subject_name())?;
    } else {
        cert_builder.set_issuer_name(&name)?;
    }
    cert_builder.set_pubkey(&private_key)?;
    cert_builder.set_serial_number(&serial_number)?;
    ......
}
Is it reasonable to set the private key as the public key of the certificate ?

I apologize for my poor English and look forward to the response. Thanks !

**Comment by n8fr8** [comment]
Yes, it is. Sorry for the slow reply. The private key will not be included in the data. You are just setting the signing key for the c2pa assertion.

You can see all the logic in kotlin in the initCredentials() method of the C2PaUtils library.
