### ISSUE TITLE
Release v14 (0.0.14-RC3) fails to generate proof

### ISSUE THREAD

**Issue by ingfabby** [guardianproject/proofmode-android#88]
Redmi 9A Android 10
Steps taken:
1. Installed the app update
2. Enable the app to run in the background
3. Took a few pictures and videos
4. Selected a picture to generate a proof, selected ProofMode and the initial screen told me no proof existed yet.
5. I selected Generate Proof, I selected "share basic" and proof was generated, I went back and selected "share robust" proof was generated
6. Selected a video to generate a proof, selected ProofMode and the initial screen told me no proof existed yet.
5. I selected Generate Proof, I selected "share basic" and proof , the screen stays on the loading phase, I went back and selected "share robust" same result.
7.  I got the same result trying to generate bulk proof selecting only images, selecting a single video, selecting multiple videos, and selecting images and videos the app stays on the loading screen and no proof is generated.
9. I uninstalled the app and tried a fresh install
10. I followed the same steps and got the same results.

**Comment by johnhess** [comment]
Having the same issue on Android 11, Samsung A21, Version 0.0.14-RC-3

**Comment by n8fr8** [comment]
New release for testing: https://github.com/guardianproject/proofmode/releases/tag/0.0.15-BETA-1
