### ISSUE TITLE
Release v14 (0.0.14-RC3) Stales Alcatel -Android 10

### ISSUE THREAD

**Issue by ingfabby** [guardianproject/proofmode-android#89]
Alcatel 5002c
Steps taken:
1. Installed the app update
2. Enable the app to run in the background
3. Took a few pictures and videos
4. Selected a picture to generate a proof, selected ProofMode and the initial screen told me no proof existed yet.
5. I selected Generate Proof, on the next screen I selected "share basic proof" and the proof was created
6. I went back and selected "share robust", the proof was created
7.  I tried to generate bulk proof selecting only images, and basic and bulk proof was generated
8.  Proof was not generated when selecting a single video, selecting multiple videos, and images and videos.
9. I uninstalled the app and tried a fresh install
10. I followed the same steps and got the same result.

**Comment by n8fr8** [comment]
Seems like the worker is not being triggered on new images being captured.

**Comment by n8fr8** [comment]
New release for testing: https://github.com/guardianproject/proofmode/releases/tag/0.0.15-BETA-1

**Comment by ingfabby** [comment]
Version 0.0.15-BETA-1
Android 12
Steps followed
1. I installed the new Beta release and enabled it to have access to storage and camera
2. Took a picture and a video
3. Open the picture, selected share with ProofMode
4. Selected "Generate Proof"
5. Selected "Basic Proof" The app stays on the loading screen, proof is not generated
6. Same results for the video file

https://user-images.githubusercontent.com/28932186/165587845-008d632f-2092-4682-b078-b5374689376d.mp4

**Comment by n8fr8** [comment]
Please test:
https://github.com/guardianproject/proofmode/releases/download/0.0.15-BETA-3/ProofMode-0.0.15-BETA-3-artwork-release.apk
