### ISSUE TITLE
JSON metadata, not just CSV

### ISSUE THREAD

**Issue by makeworld-the-better-one** [guardianproject/proofmode-android#99]
JSON is easier to parse than CSV, and rigorously defined. If the column order of the CSV is changed that could break downstream parsers, but JSON dictionaries are unordered, preventing that issue. It would be great if ProofMode added JSON output, containing the same info the CSV currently does.

**Comment by n8fr8** [comment]
Here's a sample of new proof.json output... just a quick port of CSV to JSON. Will work on more complete spec in the future, but for now this will be included in proof.zip

{"File Hash SHA256":"7cbce6f4ec442fec87b038e4f1c9dc5ec7ca33d5558ac1503172cc23d79804f9","Locale":"USA","SafetyCheckCtsMatch":"","Location.Provider":"network","IPv6":"xxx ","IPv4":"xxx ","Location.Accuracy":"13.051","Location.Latitude":"xxx","Language":"English","NetworkType":"Wifi","Network":"Connected","Manufacturer":"Google","DataType":"Mobile Data LTE","Hardware":"Google Pixel 4a","ScreenSize":"5.447290485444346","Wifi MAC":"","Notes":"ProofMode v0.0.16-ALPHA-2","DeviceID":"5upgzgbtn4s5kkg3m29v2in2e","Location.Longitude":"xxx","Location.Bearing":"0.0","SafetyCheckBasicIntegrity":"","Location.Time":"1654572792760","File Modified":"Tuesday, June 7, 2022 12:17:59 AM Eastern Daylight Time","CellInfo":"[{\"cellId\":13796615,\"tac\":22005,\"dbm\":-111},{\"cellId\":2147483647,\"tac\":2147483647,\"dbm\":-107},{\"cellId\":2147483647,\"tac\":2147483647,\"dbm\":-111}]","SafetyCheck":"","Location.Altitude":"-6.299999713897705","SafetyCheckTimestamp":"","Proof Generated":"Tuesday, June 7, 2022 12:19:09 AM Eastern Daylight Time","File Path":"\/storage\/emulated\/0\/DCIM\/Camera\/PXL_20220607_041757542.MP.jpg","Location.Speed":"0.0"}

**Comment by makeworld-the-better-one** [comment]
This is working on the latest Google Play store version.
